/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameobject.collider;

import gameobject.model.Model;
import javafx.geometry.Point2D;
import util.Const;

/**
 * Handles Collider creation
 * @author Radek
 */
public class ColliderBuilder {
    
    //<editor-fold defaultstate="collapsed" desc="Singleton- inst(), cons()">
    private static ColliderBuilder instance;
    
    private ColliderBuilder() {
    }
    
    public static ColliderBuilder inst() {
        if(instance == null) {
            instance= new ColliderBuilder();
        }
        return instance;
    }
    //</editor-fold>
    
    
    /**
     * Generates new collider
     * @param m Model of the gameObject- required for image size
     * @param type Type- modifies the size by %
     * @param offset Point2D offset of the collider compared to image
     * @param trigger Is this collider a trigger.
     * @return Returns collider, generated by specified parameters
     */
    public Collider buildNew(Model m, ColliderType type, Point2D offset, boolean trigger) {
        Point2D siz= m.getSizeOffset();
        
        switch(type) {
            case CREATURE:
                siz= new Point2D(siz.getX()* Const.IMG_CREATURE_SCALE, siz.getY());
                break;
            case HALF_Y:
                siz= new Point2D(siz.getX(), siz.getY() * 0.5);
                break;
            case HALF_X:
                siz= new Point2D(siz.getX()* 0.5, siz.getY());
                break;
            case HALF:
                siz= siz.multiply(0.5);
                break;
            case DOUBLE:
                siz= siz.multiply(1/Const.IMG_OFFSET_SCALE);
                break;
            case MIDWAY:
                siz= siz.multiply(0.77);
                break;
            case HALF_SMALL_ONLY:
            case SMALL_ONLY:
                siz= siz.multiply(0.5);
                double smaller= siz.getX() > siz.getY() ? siz.getX() : siz.getY();
                siz= new Point2D(smaller, smaller);
                break;
            case NORMAL:
                break;
        }
        return new Collider(trigger, offset, (int)siz.getX(), (int)siz.getY());
    }
}
